### ISSUE TITLE
files固化编译，默认打开，启动时还是默认关闭

### ISSUE THREAD

**Issue by mjyhj** [lwz322/luci-app-frps#1]
config里option enabled '1'
但是编译完，LUCI里，启动后还是会没打勾，未运行

另外检测状态能否改成类似这样，并且加入WEB访问入口

![1](https://user-images.githubusercontent.com/22577418/77243823-733cd380-6c49-11ea-9031-3710ffc2f697.png)

**Comment by mjyhj** [comment]
还有个问题，这翻译
![2](https://user-images.githubusercontent.com/22577418/77243833-923b6580-6c49-11ea-921e-61ddaec73929.png)

**Comment by lwz322** [comment]
files固化编译是什么..？
检查运行状态那里我这边是正常的，检查下frps的文件路径和执行权限
或者能用命令直接运行frps也行，我遇到过部分架构下frps运行不了的问题，后面换frps程序解决的

检测状态改动和WEB访问入口，有兴趣改动的话，欢迎PR（这段时间事情比较多，我写luci-app是新手，主要是为了简化配置以及守护进程）

翻译问题，应该是少了几个换行，已修复，lean那边等会PR

这个仓库我还没搞清楚为什么编译不了中文...（应该是Makefile的问题）

**Comment by mjyhj** [comment]
files 固化编译，就是把我配置的config/frps ，默认编译进固件里
会覆盖掉默认编译生成的/etc/config/frps，变成我自己保存好的frps
然后里面config里面这个参数option enabled '1'
启动固件后，LUCI竟然显示未运行，启动那也没打勾

**Comment by lwz322** [comment]
你重启下服务试下
```
service frps start
```
