### ISSUE TITLE
Dashboard 添加进 luci

### ISSUE THREAD

**Issue by willisworley** [lwz322/luci-app-frps#2]
前排支持

**Comment by willisworley** [comment]
老铁，请问你那个源码默认配置文件在哪？，如：

此份为linux 下的frps ini

https://s1.ax1x.com/2020/03/26/8xImhd.png

**Comment by lwz322** [comment]
Dashboard的设置在luci是有的
![image](https://user-images.githubusercontent.com/21271001/77605093-02e6c880-6f4f-11ea-86bb-d84f235f636b.png)
就功能方面而言，写luci的时候我是按照官方完整的配置文件写的，后续又添加了额外的自定义
基本上不用担心缺少功能的问题

对于配置文件，之前我用了很长一段时间的ini配置文件+screen，稳定，就是修改配置不方便，openwrt上因为设备性能有限，偶尔进程会挂掉
之所以写luci，一个是为了注册守护进程（自启以及维持运行）
另外就是为了配置上稍微方便一点，luci的配置在config文件夹，启动服务时会把uci配置转换成ini的格式传递给frps，因为守护进程的uci校验的存在，你修改ini也没用

**Comment by willisworley** [comment]
@lwz322 我编译的可能是你8九天前的版本，我想修改你源码里的config，token、port等之类的参数。没找到conf

**Comment by lwz322** [comment]
@willisworley  在luci上直接修改就好了 （八九天前的版本就添加了 额外设置和TLS）
![image](https://user-images.githubusercontent.com/21271001/77606500-a2f22100-6f52-11ea-8570-240e17a43428.png)
luci上修改完，就保存到config文件了 /etc/config/frps
