### ISSUE TITLE
安装后启动文件权限不对

### ISSUE THREAD

**Issue by icksky** [lwz322/luci-app-frps#3]
斐讯K3
lede

安装后 `/etc/init.d/fprs` 文件的权限不对(`-rw-rw-r--    1 root     root          4045 Feb 28  2020 frps`), 导致无法启动

**Comment by lwz322** [comment]
刚刚用release的ipk包安装试了下，并没有遇到这个问题
![image](https://user-images.githubusercontent.com/21271001/129722029-0e9e26a0-69d9-493d-ac37-51ac03f10191.png)

**Comment by icksky** [comment]
可能是我K3环境的原因 之前装其他包也出现这个问题. 多谢~
